// French vocabulary — same English prompts as words.js
const frenchWords = [
  // Greetings & basics
  { english: "hello / bye (informal)", translations: ["salut"] },
  { english: "hello (formal)", translations: ["bonjour"] },
  { english: "good morning", translations: ["bonjour"] },
  { english: "good evening", translations: ["bonsoir"] },
  { english: "good night", translations: ["bonne nuit"] },
  { english: "goodbye", translations: ["au revoir"] },
  { english: "please", translations: ["s'il vous plaît", "s'il te plaît"] },
  { english: "thank you", translations: ["merci"] },
  { english: "you're welcome", translations: ["de rien"] },
  { english: "excuse me (informal)", translations: ["excuse-moi"] },
  { english: "excuse me (formal)", translations: ["excusez-moi"] },
  { english: "sorry", translations: ["désolé", "pardon"] },
  { english: "yes", translations: ["oui"] },
  { english: "no", translations: ["non"] },
  { english: "of course", translations: ["bien sûr"] },
  { english: "ok / alright", translations: ["d'accord", "okay"] },
  { english: "I understand", translations: ["je comprends"] },
  { english: "I don't understand", translations: ["je ne comprends pas"] },
  { english: "I don't know", translations: ["je ne sais pas"] },

  // Pronouns
  { english: "I", translations: ["je"] },
  { english: "you (singular)", translations: ["tu"] },
  { english: "he", translations: ["il"] },
  { english: "she", translations: ["elle"] },
  { english: "we", translations: ["nous", "on"] },
  { english: "you (plural)", translations: ["vous"] },
  { english: "they", translations: ["ils", "elles"] },

  // Numbers
  { english: "one", translations: ["un"] },
  { english: "two", translations: ["deux"] },
  { english: "three", translations: ["trois"] },
  { english: "four", translations: ["quatre"] },
  { english: "five", translations: ["cinq"] },
  { english: "six", translations: ["six"] },
  { english: "seven", translations: ["sept"] },
  { english: "eight", translations: ["huit"] },
  { english: "nine", translations: ["neuf"] },
  { english: "ten", translations: ["dix"] },
  { english: "eleven", translations: ["onze"] },
  { english: "twelve", translations: ["douze"] },
  { english: "thirteen", translations: ["treize"] },
  { english: "fourteen", translations: ["quatorze"] },
  { english: "fifteen", translations: ["quinze"] },
  { english: "sixteen", translations: ["seize"] },
  { english: "seventeen", translations: ["dix-sept"] },
  { english: "eighteen", translations: ["dix-huit"] },
  { english: "nineteen", translations: ["dix-neuf"] },
  { english: "twenty", translations: ["vingt"] },
  { english: "thirty", translations: ["trente"] },
  { english: "forty", translations: ["quarante"] },
  { english: "fifty", translations: ["cinquante"] },
  { english: "one hundred", translations: ["cent"] },
  { english: "one thousand", translations: ["mille"] },
  { english: "first", translations: ["premier"] },
  { english: "second", translations: ["deuxième", "second"] },
  { english: "third", translations: ["troisième"] },

  // Days
  { english: "Monday", translations: ["lundi"] },
  { english: "Tuesday", translations: ["mardi"] },
  { english: "Wednesday", translations: ["mercredi"] },
  { english: "Thursday", translations: ["jeudi"] },
  { english: "Friday", translations: ["vendredi"] },
  { english: "Saturday", translations: ["samedi"] },
  { english: "Sunday", translations: ["dimanche"] },
  { english: "day", translations: ["jour"] },
  { english: "week", translations: ["semaine"] },
  { english: "weekend", translations: ["week-end"] },

  // Months
  { english: "January", translations: ["janvier"] },
  { english: "February", translations: ["février"] },
  { english: "March", translations: ["mars"] },
  { english: "April", translations: ["avril"] },
  { english: "May", translations: ["mai"] },
  { english: "June", translations: ["juin"] },
  { english: "July", translations: ["juillet"] },
  { english: "August", translations: ["août"] },
  { english: "September", translations: ["septembre"] },
  { english: "October", translations: ["octobre"] },
  { english: "November", translations: ["novembre"] },
  { english: "December", translations: ["décembre"] },
  { english: "month", translations: ["mois"] },
  { english: "year", translations: ["an", "année"] },

  // Time
  { english: "time", translations: ["temps"] },
  { english: "hour", translations: ["heure"] },
  { english: "minute", translations: ["minute"] },
  { english: "second (time)", translations: ["seconde"] },
  { english: "morning", translations: ["matin"] },
  { english: "afternoon", translations: ["après-midi"] },
  { english: "evening", translations: ["soir"] },
  { english: "night", translations: ["nuit"] },
  { english: "today", translations: ["aujourd'hui"] },
  { english: "yesterday", translations: ["hier"] },
  { english: "tomorrow", translations: ["demain"] },
  { english: "now", translations: ["maintenant"] },
  { english: "soon", translations: ["bientôt"] },
  { english: "late", translations: ["tard"] },
  { english: "early", translations: ["tôt"] },
  { english: "always", translations: ["toujours"] },
  { english: "never", translations: ["jamais"] },
  { english: "sometimes", translations: ["parfois", "quelquefois"] },
  { english: "often", translations: ["souvent"] },
  { english: "already", translations: ["déjà"] },
  { english: "still / yet", translations: ["encore", "toujours"] },
  { english: "again", translations: ["encore", "de nouveau"] },

  // Colours
  { english: "red", translations: ["rouge"] },
  { english: "blue", translations: ["bleu"] },
  { english: "green", translations: ["vert"] },
  { english: "yellow", translations: ["jaune"] },
  { english: "black", translations: ["noir"] },
  { english: "white", translations: ["blanc"] },
  { english: "orange", translations: ["orange"] },
  { english: "purple", translations: ["violet"] },
  { english: "pink", translations: ["rose"] },
  { english: "brown", translations: ["marron"] },
  { english: "grey", translations: ["gris"] },
  { english: "light blue", translations: ["bleu clair"] },

  // Family
  { english: "mother", translations: ["mère", "maman"] },
  { english: "father", translations: ["père", "papa"] },
  { english: "brother", translations: ["frère"] },
  { english: "sister", translations: ["sœur"] },
  { english: "son", translations: ["fils"] },
  { english: "daughter", translations: ["fille"] },
  { english: "grandmother", translations: ["grand-mère"] },
  { english: "grandfather", translations: ["grand-père"] },
  { english: "aunt", translations: ["tante"] },
  { english: "uncle", translations: ["oncle"] },
  { english: "husband", translations: ["mari"] },
  { english: "wife", translations: ["femme"] },
  { english: "family", translations: ["famille"] },
  { english: "child", translations: ["enfant"] },
  { english: "parents", translations: ["parents"] },
  { english: "friend (male)", translations: ["ami"] },
  { english: "friend (female)", translations: ["amie"] },

  // Body
  { english: "head", translations: ["tête"] },
  { english: "face", translations: ["visage"] },
  { english: "eye", translations: ["œil"] },
  { english: "ear", translations: ["oreille"] },
  { english: "nose", translations: ["nez"] },
  { english: "mouth", translations: ["bouche"] },
  { english: "hand", translations: ["main"] },
  { english: "foot", translations: ["pied"] },
  { english: "arm", translations: ["bras"] },
  { english: "leg", translations: ["jambe"] },
  { english: "heart", translations: ["cœur"] },
  { english: "back", translations: ["dos"] },
  { english: "hair", translations: ["cheveux"] },
  { english: "teeth", translations: ["dents"] },
  { english: "finger", translations: ["doigt"] },
  { english: "shoulder", translations: ["épaule"] },
  { english: "knee", translations: ["genou"] },

  // Food & drink
  { english: "water", translations: ["eau"] },
  { english: "bread", translations: ["pain"] },
  { english: "milk", translations: ["lait"] },
  { english: "coffee", translations: ["café"] },
  { english: "wine", translations: ["vin"] },
  { english: "beer", translations: ["bière"] },
  { english: "cheese", translations: ["fromage"] },
  { english: "meat", translations: ["viande"] },
  { english: "fish", translations: ["poisson"] },
  { english: "egg", translations: ["œuf"] },
  { english: "rice", translations: ["riz"] },
  { english: "pasta", translations: ["pâtes"] },
  { english: "pizza", translations: ["pizza"] },
  { english: "apple", translations: ["pomme"] },
  { english: "orange (fruit)", translations: ["orange"] },
  { english: "banana", translations: ["banane"] },
  { english: "tomato", translations: ["tomate"] },
  { english: "onion", translations: ["oignon"] },
  { english: "garlic", translations: ["ail"] },
  { english: "salt", translations: ["sel"] },
  { english: "sugar", translations: ["sucre"] },
  { english: "oil", translations: ["huile"] },
  { english: "soup", translations: ["soupe"] },
  { english: "salad", translations: ["salade"] },
  { english: "chicken", translations: ["poulet"] },
  { english: "vegetables", translations: ["légumes"] },
  { english: "fruit", translations: ["fruit"] },
  { english: "butter", translations: ["beurre"] },
  { english: "ice cream", translations: ["glace"] },
  { english: "cake", translations: ["gâteau"] },
  { english: "chocolate", translations: ["chocolat"] },
  { english: "breakfast", translations: ["petit-déjeuner"] },
  { english: "lunch", translations: ["déjeuner"] },
  { english: "dinner", translations: ["dîner"] },

  // Common verbs (infinitive)
  { english: "to be", translations: ["être"] },
  { english: "to have", translations: ["avoir"] },
  { english: "to do / make", translations: ["faire"] },
  { english: "to go", translations: ["aller"] },
  { english: "to come", translations: ["venir"] },
  { english: "to see", translations: ["voir"] },
  { english: "to say / tell", translations: ["dire"] },
  { english: "to know (a fact)", translations: ["savoir"] },
  { english: "to know (a person)", translations: ["connaître"] },
  { english: "to want", translations: ["vouloir"] },
  { english: "to be able to", translations: ["pouvoir"] },
  { english: "to have to", translations: ["devoir"] },
  { english: "to give", translations: ["donner"] },
  { english: "to take", translations: ["prendre"] },
  { english: "to find", translations: ["trouver"] },
  { english: "to think", translations: ["penser"] },
  { english: "to speak / talk", translations: ["parler"] },
  { english: "to eat", translations: ["manger"] },
  { english: "to drink", translations: ["boire"] },
  { english: "to sleep", translations: ["dormir"] },
  { english: "to work", translations: ["travailler"] },
  { english: "to live", translations: ["vivre"] },
  { english: "to love", translations: ["aimer"] },
  { english: "to listen", translations: ["écouter"] },
  { english: "to look at", translations: ["regarder"] },
  { english: "to understand", translations: ["comprendre"] },
  { english: "to feel / hear", translations: ["sentir", "entendre"] },
  { english: "to wait", translations: ["attendre"] },
  { english: "to call", translations: ["appeler"] },
  { english: "to ask", translations: ["demander"] },
  { english: "to leave / let go", translations: ["partir", "laisser"] },
  { english: "to return", translations: ["retourner", "revenir"] },
  { english: "to enter", translations: ["entrer"] },
  { english: "to exit / go out", translations: ["sortir"] },
  { english: "to arrive", translations: ["arriver"] },
  { english: "to remember", translations: ["se souvenir"] },
  { english: "to forget", translations: ["oublier"] },
  { english: "to believe", translations: ["croire"] },
  { english: "to lose", translations: ["perdre"] },
  { english: "to die", translations: ["mourir"] },
  { english: "to become", translations: ["devenir"] },
  { english: "to bring / carry", translations: ["apporter", "porter"] },
  { english: "to put", translations: ["mettre"] },
  { english: "to try", translations: ["essayer"] },
  { english: "to use", translations: ["utiliser"] },
  { english: "to change", translations: ["changer"] },
  { english: "to finish", translations: ["finir"] },
  { english: "to start", translations: ["commencer"] },
  { english: "to play (a game)", translations: ["jouer"] },
  { english: "to play (music)", translations: ["jouer"] },
  { english: "to sing", translations: ["chanter"] },
  { english: "to dance", translations: ["danser"] },
  { english: "to read", translations: ["lire"] },
  { english: "to write", translations: ["écrire"] },
  { english: "to walk", translations: ["marcher"] },
  { english: "to run", translations: ["courir"] },
  { english: "to drive", translations: ["conduire"] },
  { english: "to travel", translations: ["voyager"] },
  { english: "to pay", translations: ["payer"] },
  { english: "to buy", translations: ["acheter"] },
  { english: "to sell", translations: ["vendre"] },
  { english: "to help", translations: ["aider"] },
  { english: "to open", translations: ["ouvrir"] },
  { english: "to close", translations: ["fermer"] },
  { english: "to laugh", translations: ["rire"] },
  { english: "to cry", translations: ["pleurer"] },
  { english: "to smile", translations: ["sourire"] },
  { english: "to teach", translations: ["enseigner"] },
  { english: "to learn", translations: ["apprendre"] },
  { english: "to study", translations: ["étudier"] },
  { english: "to cook", translations: ["cuisiner"] },
  { english: "to wash", translations: ["laver"] },
  { english: "to clean", translations: ["nettoyer"] },
  { english: "to cut", translations: ["couper"] },
  { english: "to search", translations: ["chercher"] },
  { english: "to meet", translations: ["rencontrer"] },
  { english: "to show", translations: ["montrer"] },
  { english: "to send", translations: ["envoyer"] },
  { english: "to receive", translations: ["recevoir"] },
  { english: "to hold / keep", translations: ["tenir"] },
  { english: "to stay / remain", translations: ["rester"] },
  { english: "to continue", translations: ["continuer"] },
  { english: "to hope", translations: ["espérer"] },

  // Adjectives
  { english: "good", translations: ["bon"] },
  { english: "bad / ugly", translations: ["mauvais", "laid"] },
  { english: "big / large", translations: ["grand"] },
  { english: "small", translations: ["petit"] },
  { english: "long", translations: ["long"] },
  { english: "short (length)", translations: ["court"] },
  { english: "tall / high", translations: ["grand", "haut"] },
  { english: "short (height)", translations: ["petit"] },
  { english: "fat", translations: ["gros"] },
  { english: "thin", translations: ["mince"] },
  { english: "old", translations: ["vieux"] },
  { english: "young", translations: ["jeune"] },
  { english: "new", translations: ["nouveau"] },
  { english: "hot", translations: ["chaud"] },
  { english: "cold", translations: ["froid"] },
  { english: "warm", translations: ["tiède"] },
  { english: "fast / quick", translations: ["rapide", "vite"] },
  { english: "slow", translations: ["lent"] },
  { english: "easy", translations: ["facile"] },
  { english: "difficult / hard", translations: ["difficile"] },
  { english: "beautiful", translations: ["beau", "belle"] },
  { english: "clean", translations: ["propre"] },
  { english: "dirty", translations: ["sale"] },
  { english: "full", translations: ["plein"] },
  { english: "empty", translations: ["vide"] },
  { english: "open", translations: ["ouvert"] },
  { english: "closed", translations: ["fermé"] },
  { english: "rich", translations: ["riche"] },
  { english: "poor", translations: ["pauvre"] },
  { english: "happy", translations: ["heureux", "content"] },
  { english: "sad", translations: ["triste"] },
  { english: "tired", translations: ["fatigué"] },
  { english: "sick / ill", translations: ["malade"] },
  { english: "healthy", translations: ["sain"] },
  { english: "strong", translations: ["fort"] },
  { english: "weak", translations: ["faible"] },
  { english: "quiet", translations: ["calme", "silencieux"] },
  { english: "light (weight)", translations: ["léger"] },
  { english: "heavy", translations: ["lourd"] },
  { english: "hard", translations: ["dur"] },
  { english: "soft", translations: ["doux"] },
  { english: "sweet", translations: ["sucré", "doux"] },
  { english: "salty", translations: ["salé"] },
  { english: "bitter", translations: ["amer"] },
  { english: "spicy", translations: ["épicé", "piquant"] },
  { english: "expensive", translations: ["cher"] },
  { english: "cheap", translations: ["bon marché"] },
  { english: "near", translations: ["près", "proche"] },
  { english: "far", translations: ["loin"] },
  { english: "right / correct", translations: ["correct", "juste"] },
  { english: "wrong", translations: ["faux", "incorrect"] },
  { english: "true", translations: ["vrai"] },
  { english: "false", translations: ["faux"] },
  { english: "safe / sure", translations: ["sûr"] },
  { english: "dangerous", translations: ["dangereux"] },
  { english: "important", translations: ["important"] },
  { english: "interesting", translations: ["intéressant"] },
  { english: "boring", translations: ["ennuyeux"] },
  { english: "funny / fun", translations: ["drôle", "amusant"] },
  { english: "serious", translations: ["sérieux"] },
  { english: "strange / odd", translations: ["étrange", "bizarre"] },
  { english: "normal", translations: ["normal"] },
  { english: "different", translations: ["différent"] },
  { english: "same", translations: ["même"] },
  { english: "ready", translations: ["prêt"] },
  { english: "free", translations: ["libre"] },
  { english: "possible", translations: ["possible"] },
  { english: "impossible", translations: ["impossible"] },
  { english: "incredible", translations: ["incroyable"] },
  { english: "terrible", translations: ["terrible"] },
  { english: "perfect", translations: ["parfait"] },
  { english: "fantastic", translations: ["fantastique"] },
  { english: "excellent", translations: ["excellent"] },

  // Places
  { english: "house / home", translations: ["maison"] },
  { english: "room", translations: ["chambre", "pièce"] },
  { english: "kitchen", translations: ["cuisine"] },
  { english: "bathroom", translations: ["salle de bain"] },
  { english: "bedroom", translations: ["chambre"] },
  { english: "door", translations: ["porte"] },
  { english: "window", translations: ["fenêtre"] },
  { english: "table", translations: ["table"] },
  { english: "chair", translations: ["chaise"] },
  { english: "bed", translations: ["lit"] },
  { english: "road / street", translations: ["rue", "route"] },
  { english: "city", translations: ["ville"] },
  { english: "country / nation", translations: ["pays"] },
  { english: "world", translations: ["monde"] },
  { english: "school", translations: ["école"] },
  { english: "university", translations: ["université"] },
  { english: "hospital", translations: ["hôpital"] },
  { english: "church", translations: ["église"] },
  { english: "restaurant", translations: ["restaurant"] },
  { english: "hotel", translations: ["hôtel"] },
  { english: "shop / store", translations: ["magasin"] },
  { english: "market", translations: ["marché"] },
  { english: "airport", translations: ["aéroport"] },
  { english: "station", translations: ["gare"] },
  { english: "park", translations: ["parc"] },
  { english: "office", translations: ["bureau"] },
  { english: "library", translations: ["bibliothèque"] },
  { english: "pharmacy", translations: ["pharmacie"] },
  { english: "bank", translations: ["banque"] },
  { english: "museum", translations: ["musée"] },
  { english: "cinema / movie theatre", translations: ["cinéma"] },

  // Nature
  { english: "sun", translations: ["soleil"] },
  { english: "moon", translations: ["lune"] },
  { english: "star", translations: ["étoile"] },
  { english: "sky", translations: ["ciel"] },
  { english: "earth / ground", translations: ["terre"] },
  { english: "sea", translations: ["mer"] },
  { english: "mountain", translations: ["montagne"] },
  { english: "river", translations: ["rivière", "fleuve"] },
  { english: "forest / wood", translations: ["forêt", "bois"] },
  { english: "flower", translations: ["fleur"] },
  { english: "tree", translations: ["arbre"] },
  { english: "rain", translations: ["pluie"] },
  { english: "snow", translations: ["neige"] },
  { english: "wind", translations: ["vent"] },
  { english: "fire", translations: ["feu"] },
  { english: "water", translations: ["eau"] },
  { english: "air", translations: ["air"] },
  { english: "light", translations: ["lumière"] },

  // Animals
  { english: "dog", translations: ["chien"] },
  { english: "cat", translations: ["chat"] },
  { english: "bird", translations: ["oiseau"] },
  { english: "fish", translations: ["poisson"] },
  { english: "horse", translations: ["cheval"] },
  { english: "cow", translations: ["vache"] },
  { english: "pig", translations: ["cochon"] },
  { english: "sheep", translations: ["mouton"] },
  { english: "chicken", translations: ["poulet"] },

  // Transport
  { english: "car", translations: ["voiture"] },
  { english: "bus", translations: ["bus", "autobus"] },
  { english: "train", translations: ["train"] },
  { english: "aeroplane", translations: ["avion"] },
  { english: "bicycle", translations: ["vélo", "bicyclette"] },
  { english: "boat", translations: ["bateau"] },
  { english: "ship", translations: ["navire"] },

  // People & roles
  { english: "man", translations: ["homme"] },
  { english: "woman", translations: ["femme"] },
  { english: "boy / boyfriend", translations: ["garçon", "petit ami"] },
  { english: "girl / girlfriend", translations: ["fille", "petite amie"] },
  { english: "person", translations: ["personne"] },
  { english: "doctor", translations: ["médecin", "docteur"] },
  { english: "teacher", translations: ["professeur"] },
  { english: "student", translations: ["étudiant"] },
  { english: "police", translations: ["police"] },
  { english: "lawyer", translations: ["avocat"] },

  // Abstract & common nouns
  { english: "life", translations: ["vie"] },
  { english: "love", translations: ["amour"] },
  { english: "problem", translations: ["problème"] },
  { english: "idea", translations: ["idée"] },
  { english: "word", translations: ["mot"] },
  { english: "question", translations: ["question"] },
  { english: "answer", translations: ["réponse"] },
  { english: "reason", translations: ["raison"] },
  { english: "way / manner", translations: ["façon", "manière"] },
  { english: "story / history", translations: ["histoire"] },
  { english: "truth", translations: ["vérité"] },
  { english: "peace", translations: ["paix"] },
  { english: "war", translations: ["guerre"] },
  { english: "dream", translations: ["rêve"] },
  { english: "fear", translations: ["peur"] },
  { english: "courage", translations: ["courage"] },
  { english: "luck", translations: ["chance"] },
  { english: "hope", translations: ["espoir"] },
  { english: "money", translations: ["argent"] },
  { english: "work / job", translations: ["travail"] },
  { english: "music", translations: ["musique"] },
  { english: "song", translations: ["chanson"] },
  { english: "book", translations: ["livre"] },
  { english: "letter", translations: ["lettre"] },
  { english: "language", translations: ["langue"] },
  { english: "news", translations: ["nouvelles"] },
  { english: "photo", translations: ["photo"] },
  { english: "film / movie", translations: ["film"] },
  { english: "game", translations: ["jeu"] },
  { english: "sport", translations: ["sport"] },
  { english: "football", translations: ["football", "foot"] },
  { english: "name", translations: ["nom"] },
  { english: "voice", translations: ["voix"] },
  { english: "soul", translations: ["âme"] },
  { english: "body", translations: ["corps"] },
  { english: "blood", translations: ["sang"] },
  { english: "mind", translations: ["esprit"] },
  { english: "health", translations: ["santé"] },
  { english: "place / spot", translations: ["endroit", "place"] },
  { english: "trip / journey", translations: ["voyage"] },
  { english: "key", translations: ["clé"] },
  { english: "phone", translations: ["téléphone"] },
  { english: "message", translations: ["message"] },

  // Question words & connectors
  { english: "who", translations: ["qui"] },
  { english: "what", translations: ["quoi"] },
  { english: "where", translations: ["où"] },
  { english: "when", translations: ["quand"] },
  { english: "why", translations: ["pourquoi"] },
  { english: "how", translations: ["comment"] },
  { english: "how much", translations: ["combien"] },
  { english: "how many", translations: ["combien"] },
  { english: "which", translations: ["quel", "quelle"] },
  { english: "and", translations: ["et"] },
  { english: "but", translations: ["mais"] },
  { english: "or", translations: ["ou"] },
  { english: "because", translations: ["parce que"] },
  { english: "if", translations: ["si"] },
  { english: "not", translations: ["pas", "ne pas"] },
  { english: "very", translations: ["très"] },
  { english: "also / too", translations: ["aussi"] },
  { english: "only", translations: ["seulement"] },
  { english: "maybe", translations: ["peut-être"] },
  { english: "together", translations: ["ensemble"] },
  { english: "here", translations: ["ici"] },
  { english: "there", translations: ["là"] },
  { english: "more", translations: ["plus"] },
  { english: "less", translations: ["moins"] },
  { english: "nothing", translations: ["rien"] },
  { english: "everything", translations: ["tout"] },
  { english: "everyone", translations: ["tout le monde"] },
  { english: "no one", translations: ["personne"] },
  { english: "something", translations: ["quelque chose"] },
  { english: "someone", translations: ["quelqu'un"] },
  { english: "before", translations: ["avant"] },
  { english: "after", translations: ["après"] },
  { english: "without", translations: ["sans"] },
  { english: "against", translations: ["contre"] },
  { english: "outside", translations: ["dehors"] },
  { english: "inside", translations: ["dedans"] },
  { english: "above", translations: ["au-dessus"] },
  { english: "below / under", translations: ["en dessous", "sous"] },
  { english: "near", translations: ["près"] },
  { english: "far", translations: ["loin"] },
  { english: "in front of", translations: ["devant"] },
  { english: "behind", translations: ["derrière"] },
];
