// Italian vocabulary - curated list of common words
// Format: { english: "prompt shown to user", translations: ["accepted spoken answer(s)"] }

const italianWords = [
  // Greetings & basics
  { english: "hello / bye (informal)", translations: ["ciao"] },
  { english: "hello (formal)", translations: ["salve"] },
  { english: "good morning", translations: ["buongiorno"] },
  { english: "good evening", translations: ["buonasera"] },
  { english: "good night", translations: ["buonanotte"] },
  { english: "goodbye", translations: ["arrivederci"] },
  { english: "please", translations: ["per favore"] },
  { english: "thank you", translations: ["grazie"] },
  { english: "you're welcome", translations: ["prego"] },
  { english: "excuse me (informal)", translations: ["scusa"] },
  { english: "excuse me (formal)", translations: ["scusi"] },
  { english: "sorry", translations: ["mi dispiace"] },
  { english: "yes", translations: ["sì"] },
  { english: "no", translations: ["no"] },
  { english: "of course", translations: ["certo"] },
  { english: "ok / alright", translations: ["okay", "va bene"] },
  { english: "I understand", translations: ["capisco"] },
  { english: "I don't understand", translations: ["non capisco"] },
  { english: "I don't know", translations: ["non so"] },

  // Pronouns
  { english: "I", translations: ["io"] },
  { english: "you (singular)", translations: ["tu"] },
  { english: "he", translations: ["lui"] },
  { english: "she", translations: ["lei"] },
  { english: "we", translations: ["noi"] },
  { english: "you (plural)", translations: ["voi"] },
  { english: "they", translations: ["loro"] },

  // Numbers 1–20
  { english: "one", translations: ["uno"] },
  { english: "two", translations: ["due"] },
  { english: "three", translations: ["tre"] },
  { english: "four", translations: ["quattro"] },
  { english: "five", translations: ["cinque"] },
  { english: "six", translations: ["sei"] },
  { english: "seven", translations: ["sette"] },
  { english: "eight", translations: ["otto"] },
  { english: "nine", translations: ["nove"] },
  { english: "ten", translations: ["dieci"] },
  { english: "eleven", translations: ["undici"] },
  { english: "twelve", translations: ["dodici"] },
  { english: "thirteen", translations: ["tredici"] },
  { english: "fourteen", translations: ["quattordici"] },
  { english: "fifteen", translations: ["quindici"] },
  { english: "sixteen", translations: ["sedici"] },
  { english: "seventeen", translations: ["diciassette"] },
  { english: "eighteen", translations: ["diciotto"] },
  { english: "nineteen", translations: ["diciannove"] },
  { english: "twenty", translations: ["venti"] },
  { english: "thirty", translations: ["trenta"] },
  { english: "forty", translations: ["quaranta"] },
  { english: "fifty", translations: ["cinquanta"] },
  { english: "one hundred", translations: ["cento"] },
  { english: "one thousand", translations: ["mille"] },
  { english: "first", translations: ["primo"] },
  { english: "second", translations: ["secondo"] },
  { english: "third", translations: ["terzo"] },

  // Days of the week
  { english: "Monday", translations: ["lunedì"] },
  { english: "Tuesday", translations: ["martedì"] },
  { english: "Wednesday", translations: ["mercoledì"] },
  { english: "Thursday", translations: ["giovedì"] },
  { english: "Friday", translations: ["venerdì"] },
  { english: "Saturday", translations: ["sabato"] },
  { english: "Sunday", translations: ["domenica"] },
  { english: "day", translations: ["giorno"] },
  { english: "week", translations: ["settimana"] },
  { english: "weekend", translations: ["fine settimana"] },

  // Months
  { english: "January", translations: ["gennaio"] },
  { english: "February", translations: ["febbraio"] },
  { english: "March", translations: ["marzo"] },
  { english: "April", translations: ["aprile"] },
  { english: "May", translations: ["maggio"] },
  { english: "June", translations: ["giugno"] },
  { english: "July", translations: ["luglio"] },
  { english: "August", translations: ["agosto"] },
  { english: "September", translations: ["settembre"] },
  { english: "October", translations: ["ottobre"] },
  { english: "November", translations: ["novembre"] },
  { english: "December", translations: ["dicembre"] },
  { english: "month", translations: ["mese"] },
  { english: "year", translations: ["anno"] },

  // Time
  { english: "time", translations: ["tempo"] },
  { english: "hour", translations: ["ora"] },
  { english: "minute", translations: ["minuto"] },
  { english: "second (time)", translations: ["secondo"] },
  { english: "morning", translations: ["mattina"] },
  { english: "afternoon", translations: ["pomeriggio"] },
  { english: "evening", translations: ["sera"] },
  { english: "night", translations: ["notte"] },
  { english: "today", translations: ["oggi"] },
  { english: "yesterday", translations: ["ieri"] },
  { english: "tomorrow", translations: ["domani"] },
  { english: "now", translations: ["adesso", "ora"] },
  { english: "soon", translations: ["presto"] },
  { english: "late", translations: ["tardi"] },
  { english: "early", translations: ["presto"] },
  { english: "always", translations: ["sempre"] },
  { english: "never", translations: ["mai"] },
  { english: "sometimes", translations: ["a volte"] },
  { english: "often", translations: ["spesso"] },
  { english: "already", translations: ["già"] },
  { english: "still / yet", translations: ["ancora"] },
  { english: "again", translations: ["di nuovo"] },

  // Colors
  { english: "red", translations: ["rosso"] },
  { english: "blue", translations: ["blu"] },
  { english: "green", translations: ["verde"] },
  { english: "yellow", translations: ["giallo"] },
  { english: "black", translations: ["nero"] },
  { english: "white", translations: ["bianco"] },
  { english: "orange", translations: ["arancione"] },
  { english: "purple", translations: ["viola"] },
  { english: "pink", translations: ["rosa"] },
  { english: "brown", translations: ["marrone"] },
  { english: "grey", translations: ["grigio"] },
  { english: "light blue", translations: ["azzurro"] },

  // Family
  { english: "mother", translations: ["madre", "mamma"] },
  { english: "father", translations: ["padre", "papà"] },
  { english: "brother", translations: ["fratello"] },
  { english: "sister", translations: ["sorella"] },
  { english: "son", translations: ["figlio"] },
  { english: "daughter", translations: ["figlia"] },
  { english: "grandmother", translations: ["nonna"] },
  { english: "grandfather", translations: ["nonno"] },
  { english: "aunt", translations: ["zia"] },
  { english: "uncle", translations: ["zio"] },
  { english: "husband", translations: ["marito"] },
  { english: "wife", translations: ["moglie"] },
  { english: "family", translations: ["famiglia"] },
  { english: "child", translations: ["bambino"] },
  { english: "parents", translations: ["genitori"] },
  { english: "friend (male)", translations: ["amico"] },
  { english: "friend (female)", translations: ["amica"] },

  // Body
  { english: "head", translations: ["testa"] },
  { english: "face", translations: ["faccia"] },
  { english: "eye", translations: ["occhio"] },
  { english: "ear", translations: ["orecchio"] },
  { english: "nose", translations: ["naso"] },
  { english: "mouth", translations: ["bocca"] },
  { english: "hand", translations: ["mano"] },
  { english: "foot", translations: ["piede"] },
  { english: "arm", translations: ["braccio"] },
  { english: "leg", translations: ["gamba"] },
  { english: "heart", translations: ["cuore"] },
  { english: "back", translations: ["schiena"] },
  { english: "hair", translations: ["capelli"] },
  { english: "teeth", translations: ["denti"] },
  { english: "finger", translations: ["dito"] },
  { english: "shoulder", translations: ["spalla"] },
  { english: "knee", translations: ["ginocchio"] },

  // Food & drink
  { english: "water", translations: ["acqua"] },
  { english: "bread", translations: ["pane"] },
  { english: "milk", translations: ["latte"] },
  { english: "coffee", translations: ["caffè"] },
  { english: "wine", translations: ["vino"] },
  { english: "beer", translations: ["birra"] },
  { english: "cheese", translations: ["formaggio"] },
  { english: "meat", translations: ["carne"] },
  { english: "fish", translations: ["pesce"] },
  { english: "egg", translations: ["uovo"] },
  { english: "rice", translations: ["riso"] },
  { english: "pasta", translations: ["pasta"] },
  { english: "pizza", translations: ["pizza"] },
  { english: "apple", translations: ["mela"] },
  { english: "orange (fruit)", translations: ["arancia"] },
  { english: "banana", translations: ["banana"] },
  { english: "tomato", translations: ["pomodoro"] },
  { english: "onion", translations: ["cipolla"] },
  { english: "garlic", translations: ["aglio"] },
  { english: "salt", translations: ["sale"] },
  { english: "sugar", translations: ["zucchero"] },
  { english: "oil", translations: ["olio"] },
  { english: "soup", translations: ["zuppa"] },
  { english: "salad", translations: ["insalata"] },
  { english: "chicken", translations: ["pollo"] },
  { english: "vegetables", translations: ["verdura"] },
  { english: "fruit", translations: ["frutta"] },
  { english: "butter", translations: ["burro"] },
  { english: "ice cream", translations: ["gelato"] },
  { english: "cake", translations: ["torta"] },
  { english: "chocolate", translations: ["cioccolato"] },
  { english: "breakfast", translations: ["colazione"] },
  { english: "lunch", translations: ["pranzo"] },
  { english: "dinner", translations: ["cena"] },

  // Common verbs (infinitive)
  { english: "to be", translations: ["essere"] },
  { english: "to have", translations: ["avere"] },
  { english: "to do / make", translations: ["fare"] },
  { english: "to go", translations: ["andare"] },
  { english: "to come", translations: ["venire"] },
  { english: "to see", translations: ["vedere"] },
  { english: "to say / tell", translations: ["dire"] },
  { english: "to know (a fact)", translations: ["sapere"] },
  { english: "to know (a person)", translations: ["conoscere"] },
  { english: "to want", translations: ["volere"] },
  { english: "to be able to", translations: ["potere"] },
  { english: "to have to", translations: ["dovere"] },
  { english: "to give", translations: ["dare"] },
  { english: "to take", translations: ["prendere"] },
  { english: "to find", translations: ["trovare"] },
  { english: "to think", translations: ["pensare"] },
  { english: "to speak / talk", translations: ["parlare"] },
  { english: "to eat", translations: ["mangiare"] },
  { english: "to drink", translations: ["bere"] },
  { english: "to sleep", translations: ["dormire"] },
  { english: "to work", translations: ["lavorare"] },
  { english: "to live", translations: ["vivere"] },
  { english: "to love", translations: ["amare"] },
  { english: "to listen", translations: ["ascoltare"] },
  { english: "to look at", translations: ["guardare"] },
  { english: "to understand", translations: ["capire"] },
  { english: "to feel / hear", translations: ["sentire"] },
  { english: "to wait", translations: ["aspettare"] },
  { english: "to call", translations: ["chiamare"] },
  { english: "to ask", translations: ["chiedere"] },
  { english: "to leave / let go", translations: ["lasciare"] },
  { english: "to return", translations: ["tornare"] },
  { english: "to enter", translations: ["entrare"] },
  { english: "to exit / go out", translations: ["uscire"] },
  { english: "to arrive", translations: ["arrivare"] },
  { english: "to remember", translations: ["ricordare"] },
  { english: "to forget", translations: ["dimenticare"] },
  { english: "to believe", translations: ["credere"] },
  { english: "to lose", translations: ["perdere"] },
  { english: "to die", translations: ["morire"] },
  { english: "to become", translations: ["diventare"] },
  { english: "to bring / carry", translations: ["portare"] },
  { english: "to put", translations: ["mettere"] },
  { english: "to try", translations: ["provare"] },
  { english: "to use", translations: ["usare"] },
  { english: "to change", translations: ["cambiare"] },
  { english: "to finish", translations: ["finire"] },
  { english: "to start", translations: ["iniziare", "cominciare"] },
  { english: "to play (a game)", translations: ["giocare"] },
  { english: "to play (music)", translations: ["suonare"] },
  { english: "to sing", translations: ["cantare"] },
  { english: "to dance", translations: ["ballare"] },
  { english: "to read", translations: ["leggere"] },
  { english: "to write", translations: ["scrivere"] },
  { english: "to walk", translations: ["camminare"] },
  { english: "to run", translations: ["correre"] },
  { english: "to drive", translations: ["guidare"] },
  { english: "to travel", translations: ["viaggiare"] },
  { english: "to pay", translations: ["pagare"] },
  { english: "to buy", translations: ["comprare"] },
  { english: "to sell", translations: ["vendere"] },
  { english: "to help", translations: ["aiutare"] },
  { english: "to open", translations: ["aprire"] },
  { english: "to close", translations: ["chiudere"] },
  { english: "to laugh", translations: ["ridere"] },
  { english: "to cry", translations: ["piangere"] },
  { english: "to smile", translations: ["sorridere"] },
  { english: "to teach", translations: ["insegnare"] },
  { english: "to learn", translations: ["imparare"] },
  { english: "to study", translations: ["studiare"] },
  { english: "to cook", translations: ["cucinare"] },
  { english: "to wash", translations: ["lavare"] },
  { english: "to clean", translations: ["pulire"] },
  { english: "to cut", translations: ["tagliare"] },
  { english: "to search", translations: ["cercare"] },
  { english: "to meet", translations: ["incontrare"] },
  { english: "to show", translations: ["mostrare"] },
  { english: "to send", translations: ["mandare", "inviare"] },
  { english: "to receive", translations: ["ricevere"] },
  { english: "to hold / keep", translations: ["tenere"] },
  { english: "to stay / remain", translations: ["restare"] },
  { english: "to continue", translations: ["continuare"] },
  { english: "to hope", translations: ["sperare"] },

  // Common adjectives
  { english: "good", translations: ["buono"] },
  { english: "bad / ugly", translations: ["brutto", "cattivo"] },
  { english: "big / large", translations: ["grande"] },
  { english: "small", translations: ["piccolo"] },
  { english: "long", translations: ["lungo"] },
  { english: "short (length)", translations: ["corto"] },
  { english: "tall / high", translations: ["alto"] },
  { english: "short (height)", translations: ["basso"] },
  { english: "fat", translations: ["grasso"] },
  { english: "thin", translations: ["magro"] },
  { english: "old", translations: ["vecchio"] },
  { english: "young", translations: ["giovane"] },
  { english: "new", translations: ["nuovo"] },
  { english: "hot", translations: ["caldo"] },
  { english: "cold", translations: ["freddo"] },
  { english: "warm", translations: ["tiepido"] },
  { english: "fast / quick", translations: ["veloce"] },
  { english: "slow", translations: ["lento"] },
  { english: "easy", translations: ["facile"] },
  { english: "difficult / hard", translations: ["difficile"] },
  { english: "beautiful", translations: ["bello"] },
  { english: "clean", translations: ["pulito"] },
  { english: "dirty", translations: ["sporco"] },
  { english: "full", translations: ["pieno"] },
  { english: "empty", translations: ["vuoto"] },
  { english: "open", translations: ["aperto"] },
  { english: "closed", translations: ["chiuso"] },
  { english: "rich", translations: ["ricco"] },
  { english: "poor", translations: ["povero"] },
  { english: "happy", translations: ["felice", "contento"] },
  { english: "sad", translations: ["triste"] },
  { english: "tired", translations: ["stanco"] },
  { english: "sick / ill", translations: ["malato"] },
  { english: "healthy", translations: ["sano"] },
  { english: "strong", translations: ["forte"] },
  { english: "weak", translations: ["debole"] },
  { english: "loud / strong", translations: ["forte"] },
  { english: "quiet", translations: ["silenzioso", "tranquillo"] },
  { english: "light (weight)", translations: ["leggero"] },
  { english: "heavy", translations: ["pesante"] },
  { english: "hard", translations: ["duro"] },
  { english: "soft", translations: ["morbido"] },
  { english: "sweet", translations: ["dolce"] },
  { english: "salty", translations: ["salato"] },
  { english: "bitter", translations: ["amaro"] },
  { english: "spicy", translations: ["piccante"] },
  { english: "expensive", translations: ["caro"] },
  { english: "cheap", translations: ["economico"] },
  { english: "near", translations: ["vicino"] },
  { english: "far", translations: ["lontano"] },
  { english: "right / correct", translations: ["giusto"] },
  { english: "wrong", translations: ["sbagliato"] },
  { english: "true", translations: ["vero"] },
  { english: "false", translations: ["falso"] },
  { english: "safe / sure", translations: ["sicuro"] },
  { english: "dangerous", translations: ["pericoloso"] },
  { english: "important", translations: ["importante"] },
  { english: "interesting", translations: ["interessante"] },
  { english: "boring", translations: ["noioso"] },
  { english: "funny / fun", translations: ["divertente"] },
  { english: "serious", translations: ["serio"] },
  { english: "strange / odd", translations: ["strano"] },
  { english: "normal", translations: ["normale"] },
  { english: "different", translations: ["diverso"] },
  { english: "same", translations: ["stesso"] },
  { english: "ready", translations: ["pronto"] },
  { english: "free", translations: ["libero"] },
  { english: "possible", translations: ["possibile"] },
  { english: "impossible", translations: ["impossibile"] },
  { english: "incredible", translations: ["incredibile"] },
  { english: "terrible", translations: ["terribile"] },
  { english: "perfect", translations: ["perfetto"] },
  { english: "fantastic", translations: ["fantastico"] },
  { english: "excellent", translations: ["ottimo"] },

  // Common nouns — places
  { english: "house / home", translations: ["casa"] },
  { english: "room", translations: ["stanza", "camera"] },
  { english: "kitchen", translations: ["cucina"] },
  { english: "bathroom", translations: ["bagno"] },
  { english: "bedroom", translations: ["camera da letto"] },
  { english: "door", translations: ["porta"] },
  { english: "window", translations: ["finestra"] },
  { english: "table", translations: ["tavolo"] },
  { english: "chair", translations: ["sedia"] },
  { english: "bed", translations: ["letto"] },
  { english: "road / street", translations: ["strada"] },
  { english: "city", translations: ["città"] },
  { english: "country / nation", translations: ["paese", "nazione"] },
  { english: "world", translations: ["mondo"] },
  { english: "school", translations: ["scuola"] },
  { english: "university", translations: ["università"] },
  { english: "hospital", translations: ["ospedale"] },
  { english: "church", translations: ["chiesa"] },
  { english: "restaurant", translations: ["ristorante"] },
  { english: "hotel", translations: ["albergo"] },
  { english: "shop / store", translations: ["negozio"] },
  { english: "market", translations: ["mercato"] },
  { english: "airport", translations: ["aeroporto"] },
  { english: "station", translations: ["stazione"] },
  { english: "park", translations: ["parco"] },
  { english: "office", translations: ["ufficio"] },
  { english: "library", translations: ["biblioteca"] },
  { english: "pharmacy", translations: ["farmacia"] },
  { english: "bank", translations: ["banca"] },
  { english: "museum", translations: ["museo"] },
  { english: "cinema / movie theatre", translations: ["cinema"] },

  // Nature
  { english: "sun", translations: ["sole"] },
  { english: "moon", translations: ["luna"] },
  { english: "star", translations: ["stella"] },
  { english: "sky", translations: ["cielo"] },
  { english: "earth / ground", translations: ["terra"] },
  { english: "sea", translations: ["mare"] },
  { english: "mountain", translations: ["montagna"] },
  { english: "river", translations: ["fiume"] },
  { english: "forest / wood", translations: ["bosco", "foresta"] },
  { english: "flower", translations: ["fiore"] },
  { english: "tree", translations: ["albero"] },
  { english: "rain", translations: ["pioggia"] },
  { english: "snow", translations: ["neve"] },
  { english: "wind", translations: ["vento"] },
  { english: "fire", translations: ["fuoco"] },
  { english: "water", translations: ["acqua"] },
  { english: "air", translations: ["aria"] },
  { english: "light", translations: ["luce"] },

  // Animals
  { english: "dog", translations: ["cane"] },
  { english: "cat", translations: ["gatto"] },
  { english: "bird", translations: ["uccello"] },
  { english: "fish", translations: ["pesce"] },
  { english: "horse", translations: ["cavallo"] },
  { english: "cow", translations: ["mucca"] },
  { english: "pig", translations: ["maiale"] },
  { english: "sheep", translations: ["pecora"] },
  { english: "chicken", translations: ["pollo"] },

  // Transport
  { english: "car", translations: ["macchina", "auto"] },
  { english: "bus", translations: ["autobus"] },
  { english: "train", translations: ["treno"] },
  { english: "aeroplane", translations: ["aereo"] },
  { english: "bicycle", translations: ["bicicletta"] },
  { english: "boat", translations: ["barca"] },
  { english: "ship", translations: ["nave"] },

  // Common nouns — people & roles
  { english: "man", translations: ["uomo"] },
  { english: "woman", translations: ["donna"] },
  { english: "boy / boyfriend", translations: ["ragazzo"] },
  { english: "girl / girlfriend", translations: ["ragazza"] },
  { english: "person", translations: ["persona"] },
  { english: "doctor", translations: ["dottore", "medico"] },
  { english: "teacher", translations: ["insegnante"] },
  { english: "student", translations: ["studente"] },
  { english: "police", translations: ["polizia"] },
  { english: "lawyer", translations: ["avvocato"] },

  // Abstract & common nouns
  { english: "life", translations: ["vita"] },
  { english: "love", translations: ["amore"] },
  { english: "problem", translations: ["problema"] },
  { english: "idea", translations: ["idea"] },
  { english: "word", translations: ["parola"] },
  { english: "question", translations: ["domanda"] },
  { english: "answer", translations: ["risposta"] },
  { english: "reason", translations: ["ragione", "motivo"] },
  { english: "way / manner", translations: ["modo"] },
  { english: "story / history", translations: ["storia"] },
  { english: "truth", translations: ["verità"] },
  { english: "peace", translations: ["pace"] },
  { english: "war", translations: ["guerra"] },
  { english: "dream", translations: ["sogno"] },
  { english: "fear", translations: ["paura"] },
  { english: "courage", translations: ["coraggio"] },
  { english: "luck", translations: ["fortuna"] },
  { english: "hope", translations: ["speranza"] },
  { english: "money", translations: ["soldi"] },
  { english: "work / job", translations: ["lavoro"] },
  { english: "music", translations: ["musica"] },
  { english: "song", translations: ["canzone"] },
  { english: "book", translations: ["libro"] },
  { english: "letter", translations: ["lettera"] },
  { english: "language", translations: ["lingua"] },
  { english: "news", translations: ["notizie"] },
  { english: "photo", translations: ["foto"] },
  { english: "film / movie", translations: ["film"] },
  { english: "game", translations: ["gioco"] },
  { english: "sport", translations: ["sport"] },
  { english: "football", translations: ["calcio"] },
  { english: "name", translations: ["nome"] },
  { english: "voice", translations: ["voce"] },
  { english: "soul", translations: ["anima"] },
  { english: "body", translations: ["corpo"] },
  { english: "blood", translations: ["sangue"] },
  { english: "mind", translations: ["mente"] },
  { english: "heart", translations: ["cuore"] },
  { english: "health", translations: ["salute"] },
  { english: "place / spot", translations: ["posto"] },
  { english: "trip / journey", translations: ["viaggio"] },
  { english: "key", translations: ["chiave"] },
  { english: "phone", translations: ["telefono"] },
  { english: "message", translations: ["messaggio"] },

  // Question words & connectors
  { english: "who", translations: ["chi"] },
  { english: "what", translations: ["cosa"] },
  { english: "where", translations: ["dove"] },
  { english: "when", translations: ["quando"] },
  { english: "why", translations: ["perché"] },
  { english: "how", translations: ["come"] },
  { english: "how much", translations: ["quanto"] },
  { english: "how many", translations: ["quanti"] },
  { english: "which", translations: ["quale"] },
  { english: "and", translations: ["e"] },
  { english: "but", translations: ["ma"] },
  { english: "or", translations: ["o"] },
  { english: "because", translations: ["perché"] },
  { english: "if", translations: ["se"] },
  { english: "not", translations: ["non"] },
  { english: "very", translations: ["molto"] },
  { english: "also / too", translations: ["anche"] },
  { english: "only", translations: ["solo", "soltanto"] },
  { english: "maybe", translations: ["forse"] },
  { english: "together", translations: ["insieme"] },
  { english: "here", translations: ["qui"] },
  { english: "there", translations: ["là", "lì"] },
  { english: "more", translations: ["più"] },
  { english: "less", translations: ["meno"] },
  { english: "nothing", translations: ["niente", "nulla"] },
  { english: "everything", translations: ["tutto"] },
  { english: "everyone", translations: ["tutti"] },
  { english: "no one", translations: ["nessuno"] },
  { english: "something", translations: ["qualcosa"] },
  { english: "someone", translations: ["qualcuno"] },
  { english: "never", translations: ["mai"] },
  { english: "again", translations: ["ancora", "di nuovo"] },
  { english: "before", translations: ["prima"] },
  { english: "after", translations: ["dopo"] },
  { english: "without", translations: ["senza"] },
  { english: "against", translations: ["contro"] },
  { english: "outside", translations: ["fuori"] },
  { english: "inside", translations: ["dentro"] },
  { english: "above", translations: ["sopra"] },
  { english: "below / under", translations: ["sotto"] },
  { english: "near", translations: ["vicino"] },
  { english: "far", translations: ["lontano"] },
  { english: "in front of", translations: ["davanti"] },
  { english: "behind", translations: ["dietro"] },

  // Present tense conjugations — essere (to be)
  { english: "I am", translations: ["sono"] },
  { english: "you are", translations: ["sei"] },
  { english: "he/she is", translations: ["è"] },
  { english: "we are", translations: ["siamo"] },
  { english: "you all are", translations: ["siete"] },
  { english: "they are", translations: ["sono"] },

  // Present tense conjugations — avere (to have)
  { english: "I have", translations: ["ho"] },
  { english: "you have", translations: ["hai"] },
  { english: "he/she has", translations: ["ha"] },
  { english: "we have", translations: ["abbiamo"] },
  { english: "you all have", translations: ["avete"] },
  { english: "they have", translations: ["hanno"] },

  // Present tense conjugations — fare (to do/make)
  { english: "I do", translations: ["faccio"] },
  { english: "you do", translations: ["fai"] },
  { english: "he/she does", translations: ["fa"] },
  { english: "we do", translations: ["facciamo"] },
  { english: "you all do", translations: ["fate"] },
  { english: "they do", translations: ["fanno"] },

  // Present tense conjugations — andare (to go)
  { english: "I go", translations: ["vado"] },
  { english: "you go", translations: ["vai"] },
  { english: "he/she goes", translations: ["va"] },
  { english: "we go", translations: ["andiamo"] },
  { english: "you all go", translations: ["andate"] },
  { english: "they go", translations: ["vanno"] },

  // Present tense conjugations — venire (to come)
  { english: "I come", translations: ["vengo"] },
  { english: "you come", translations: ["vieni"] },
  { english: "he/she comes", translations: ["viene"] },
  { english: "we come", translations: ["veniamo"] },
  { english: "you all come", translations: ["venite"] },
  { english: "they come", translations: ["vengono"] },

  // Present tense conjugations — stare (to stay/be)
  { english: "I stay", translations: ["sto"] },
  { english: "you stay", translations: ["stai"] },
  { english: "he/she stays", translations: ["sta"] },
  { english: "we stay", translations: ["stiamo"] },
  { english: "you all stay", translations: ["state"] },
  { english: "they stay", translations: ["stanno"] },

  // Present tense conjugations — dare (to give)
  { english: "I give", translations: ["do"] },
  { english: "you give", translations: ["dai"] },
  { english: "he/she gives", translations: ["dà"] },
  { english: "we give", translations: ["diamo"] },
  { english: "you all give", translations: ["date"] },
  { english: "they give", translations: ["danno"] },

  // Present tense conjugations — volere (to want)
  { english: "I want", translations: ["voglio"] },
  { english: "you want", translations: ["vuoi"] },
  { english: "he/she wants", translations: ["vuole"] },
  { english: "we want", translations: ["vogliamo"] },
  { english: "you all want", translations: ["volete"] },
  { english: "they want", translations: ["vogliono"] },

  // Present tense conjugations — potere (to be able to)
  { english: "I can", translations: ["posso"] },
  { english: "you can", translations: ["puoi"] },
  { english: "he/she can", translations: ["può"] },
  { english: "we can", translations: ["possiamo"] },
  { english: "you all can", translations: ["potete"] },
  { english: "they can", translations: ["possono"] },

  // Present tense conjugations — dovere (to have to)
  { english: "I must", translations: ["devo"] },
  { english: "you must", translations: ["devi"] },
  { english: "he/she must", translations: ["deve"] },
  { english: "we must", translations: ["dobbiamo"] },
  { english: "you all must", translations: ["dovete"] },
  { english: "they must", translations: ["devono"] },

  // Present tense conjugations — parlare (to speak)
  { english: "I speak", translations: ["parlo"] },
  { english: "you speak", translations: ["parli"] },
  { english: "he/she speaks", translations: ["parla"] },
  { english: "we speak", translations: ["parliamo"] },
  { english: "you all speak", translations: ["parlate"] },
  { english: "they speak", translations: ["parlano"] },

  // Present tense conjugations — mangiare (to eat)
  { english: "I eat", translations: ["mangio"] },
  { english: "you eat", translations: ["mangi"] },
  { english: "he/she eats", translations: ["mangia"] },
  { english: "we eat", translations: ["mangiamo"] },
  { english: "you all eat", translations: ["mangiate"] },
  { english: "they eat", translations: ["mangiano"] },

  // Present tense conjugations — bere (to drink)
  { english: "I drink", translations: ["bevo"] },
  { english: "you drink", translations: ["bevi"] },
  { english: "he/she drinks", translations: ["beve"] },
  { english: "we drink", translations: ["beviamo"] },
  { english: "you all drink", translations: ["bevete"] },
  { english: "they drink", translations: ["bevono"] },

  // Present tense conjugations — dormire (to sleep)
  { english: "I sleep", translations: ["dormo"] },
  { english: "you sleep", translations: ["dormi"] },
  { english: "he/she sleeps", translations: ["dorme"] },
  { english: "we sleep", translations: ["dormiamo"] },
  { english: "you all sleep", translations: ["dormite"] },
  { english: "they sleep", translations: ["dormono"] },

  // Present tense conjugations — capire (to understand)
  { english: "I understand", translations: ["capisco"] },
  { english: "you understand", translations: ["capisci"] },
  { english: "he/she understands", translations: ["capisce"] },
  { english: "we understand", translations: ["capiamo"] },
  { english: "you all understand", translations: ["capite"] },
  { english: "they understand", translations: ["capiscono"] },
];
