// French vocabulary — structured by CEFR level

const frenchWordsA1 = [
  // Greetings & basics
  { english: "hello / bye (informal)", translations: ["salut"] },
  { english: "hello (formal)", translations: ["bonjour"] },
  { english: "good morning", translations: ["bonjour"] },
  { english: "good evening", translations: ["bonsoir"] },
  { english: "good night", translations: ["bonne nuit"] },
  { english: "goodbye", translations: ["au revoir"] },
  { english: "please", translations: ["s'il vous plaît", "s'il te plaît"] },
  { english: "thank you", translations: ["merci"] },
  { english: "you're welcome", translations: ["de rien"] },
  { english: "excuse me (informal)", translations: ["excuse-moi"] },
  { english: "excuse me (formal)", translations: ["excusez-moi"] },
  { english: "sorry", translations: ["désolé", "pardon"] },
  { english: "yes", translations: ["oui"] },
  { english: "no", translations: ["non"] },
  { english: "ok / alright", translations: ["d'accord"] },
  { english: "I understand", translations: ["je comprends"] },
  { english: "I don't understand", translations: ["je ne comprends pas"] },
  { english: "I don't know", translations: ["je ne sais pas"] },

  // Pronouns
  { english: "I", translations: ["je"] },
  { english: "you (singular)", translations: ["tu"] },
  { english: "he", translations: ["il"] },
  { english: "she", translations: ["elle"] },
  { english: "we", translations: ["nous", "on"] },
  { english: "you (plural)", translations: ["vous"] },
  { english: "they", translations: ["ils", "elles"] },

  // Numbers 1–10
  { english: "one", translations: ["un"] },
  { english: "two", translations: ["deux"] },
  { english: "three", translations: ["trois"] },
  { english: "four", translations: ["quatre"] },
  { english: "five", translations: ["cinq"] },
  { english: "six", translations: ["six"] },
  { english: "seven", translations: ["sept"] },
  { english: "eight", translations: ["huit"] },
  { english: "nine", translations: ["neuf"] },
  { english: "ten", translations: ["dix"] },

  // Days & basic time
  { english: "Monday", translations: ["lundi"] },
  { english: "Tuesday", translations: ["mardi"] },
  { english: "Wednesday", translations: ["mercredi"] },
  { english: "Thursday", translations: ["jeudi"] },
  { english: "Friday", translations: ["vendredi"] },
  { english: "Saturday", translations: ["samedi"] },
  { english: "Sunday", translations: ["dimanche"] },
  { english: "day", translations: ["jour"] },
  { english: "morning", translations: ["matin"] },
  { english: "afternoon", translations: ["après-midi"] },
  { english: "evening", translations: ["soir"] },
  { english: "night", translations: ["nuit"] },
  { english: "today", translations: ["aujourd'hui"] },
  { english: "yesterday", translations: ["hier"] },
  { english: "tomorrow", translations: ["demain"] },
  { english: "now", translations: ["maintenant"] },

  // Basic colours
  { english: "red", translations: ["rouge"] },
  { english: "blue", translations: ["bleu"] },
  { english: "green", translations: ["vert"] },
  { english: "yellow", translations: ["jaune"] },
  { english: "black", translations: ["noir"] },
  { english: "white", translations: ["blanc"] },
  { english: "orange", translations: ["orange"] },
  { english: "purple", translations: ["violet"] },
  { english: "pink", translations: ["rose"] },
  { english: "brown", translations: ["marron"] },
  { english: "grey", translations: ["gris"] },

  // Family
  { english: "mother", translations: ["mère", "maman"] },
  { english: "father", translations: ["père", "papa"] },
  { english: "brother", translations: ["frère"] },
  { english: "sister", translations: ["sœur"] },
  { english: "son", translations: ["fils"] },
  { english: "daughter", translations: ["fille"] },
  { english: "grandmother", translations: ["grand-mère"] },
  { english: "grandfather", translations: ["grand-père"] },
  { english: "aunt", translations: ["tante"] },
  { english: "uncle", translations: ["oncle"] },
  { english: "family", translations: ["famille"] },
  { english: "child", translations: ["enfant"] },
  { english: "friend (male)", translations: ["ami"] },
  { english: "friend (female)", translations: ["amie"] },

  // Basic body
  { english: "head", translations: ["tête"] },
  { english: "eye", translations: ["œil"] },
  { english: "ear", translations: ["oreille"] },
  { english: "nose", translations: ["nez"] },
  { english: "mouth", translations: ["bouche"] },
  { english: "hand", translations: ["main"] },
  { english: "foot", translations: ["pied"] },
  { english: "arm", translations: ["bras"] },
  { english: "leg", translations: ["jambe"] },
  { english: "heart", translations: ["cœur"] },

  // Basic food & drink
  { english: "water", translations: ["eau"] },
  { english: "bread", translations: ["pain"] },
  { english: "milk", translations: ["lait"] },
  { english: "coffee", translations: ["café"] },
  { english: "wine", translations: ["vin"] },
  { english: "cheese", translations: ["fromage"] },
  { english: "meat", translations: ["viande"] },
  { english: "fish", translations: ["poisson"] },
  { english: "egg", translations: ["œuf"] },
  { english: "rice", translations: ["riz"] },
  { english: "apple", translations: ["pomme"] },

  // Core infinitive verbs
  { english: "to be", translations: ["être"] },
  { english: "to have", translations: ["avoir"] },
  { english: "to do / make", translations: ["faire"] },
  { english: "to go", translations: ["aller"] },
  { english: "to come", translations: ["venir"] },
  { english: "to see", translations: ["voir"] },
  { english: "to say / tell", translations: ["dire"] },
  { english: "to want", translations: ["vouloir"] },
  { english: "to be able to", translations: ["pouvoir"] },
  { english: "to have to", translations: ["devoir"] },
  { english: "to give", translations: ["donner"] },
  { english: "to take", translations: ["prendre"] },
  { english: "to speak / talk", translations: ["parler"] },
  { english: "to eat", translations: ["manger"] },
  { english: "to drink", translations: ["boire"] },
  { english: "to sleep", translations: ["dormir"] },
  { english: "to work", translations: ["travailler"] },
  { english: "to live", translations: ["vivre"] },
  { english: "to love", translations: ["aimer"] },
  { english: "to understand", translations: ["comprendre"] },

  // Basic adjectives
  { english: "good", translations: ["bon"] },
  { english: "bad / ugly", translations: ["mauvais"] },
  { english: "big / large", translations: ["grand"] },
  { english: "small", translations: ["petit"] },
  { english: "hot", translations: ["chaud"] },
  { english: "cold", translations: ["froid"] },
  { english: "old", translations: ["vieux"] },
  { english: "young", translations: ["jeune"] },
  { english: "new", translations: ["nouveau"] },
  { english: "happy", translations: ["heureux", "content"] },
  { english: "sad", translations: ["triste"] },
  { english: "tired", translations: ["fatigué"] },
  { english: "beautiful", translations: ["beau", "belle"] },
  { english: "easy", translations: ["facile"] },
  { english: "difficult / hard", translations: ["difficile"] },
  { english: "fast / quick", translations: ["rapide"] },
  { english: "slow", translations: ["lent"] },

  // Basic places
  { english: "house / home", translations: ["maison"] },
  { english: "room", translations: ["chambre", "pièce"] },
  { english: "kitchen", translations: ["cuisine"] },
  { english: "door", translations: ["porte"] },
  { english: "table", translations: ["table"] },
  { english: "chair", translations: ["chaise"] },
  { english: "city", translations: ["ville"] },
  { english: "school", translations: ["école"] },
  { english: "restaurant", translations: ["restaurant"] },

  // Animals
  { english: "dog", translations: ["chien"] },
  { english: "cat", translations: ["chat"] },
  { english: "bird", translations: ["oiseau"] },
  { english: "horse", translations: ["cheval"] },
  { english: "cow", translations: ["vache"] },

  // Basic transport
  { english: "car", translations: ["voiture"] },
  { english: "bus", translations: ["bus", "autobus"] },
  { english: "train", translations: ["train"] },

  // People
  { english: "man", translations: ["homme"] },
  { english: "woman", translations: ["femme"] },
  { english: "boy", translations: ["garçon"] },
  { english: "girl", translations: ["fille"] },
  { english: "person", translations: ["personne"] },

  // Question words & basic connectors
  { english: "who", translations: ["qui"] },
  { english: "what", translations: ["quoi"] },
  { english: "where", translations: ["où"] },
  { english: "when", translations: ["quand"] },
  { english: "why", translations: ["pourquoi"] },
  { english: "how", translations: ["comment"] },
  { english: "how much / how many", translations: ["combien"] },
  { english: "and", translations: ["et"] },
  { english: "but", translations: ["mais"] },
  { english: "or", translations: ["ou"] },
  { english: "because", translations: ["parce que"] },
  { english: "not", translations: ["pas", "ne pas"] },
  { english: "very", translations: ["très"] },
  { english: "here", translations: ["ici"] },
  { english: "there", translations: ["là"] },
];

const frenchWordsA2_new = [
  // Numbers 11+
  { english: "eleven", translations: ["onze"] },
  { english: "twelve", translations: ["douze"] },
  { english: "thirteen", translations: ["treize"] },
  { english: "fourteen", translations: ["quatorze"] },
  { english: "fifteen", translations: ["quinze"] },
  { english: "sixteen", translations: ["seize"] },
  { english: "seventeen", translations: ["dix-sept"] },
  { english: "eighteen", translations: ["dix-huit"] },
  { english: "nineteen", translations: ["dix-neuf"] },
  { english: "twenty", translations: ["vingt"] },
  { english: "thirty", translations: ["trente"] },
  { english: "forty", translations: ["quarante"] },
  { english: "fifty", translations: ["cinquante"] },
  { english: "one hundred", translations: ["cent"] },
  { english: "one thousand", translations: ["mille"] },
  { english: "first", translations: ["premier"] },
  { english: "second", translations: ["deuxième", "second"] },
  { english: "third", translations: ["troisième"] },

  // Months
  { english: "January", translations: ["janvier"] },
  { english: "February", translations: ["février"] },
  { english: "March", translations: ["mars"] },
  { english: "April", translations: ["avril"] },
  { english: "May", translations: ["mai"] },
  { english: "June", translations: ["juin"] },
  { english: "July", translations: ["juillet"] },
  { english: "August", translations: ["août"] },
  { english: "September", translations: ["septembre"] },
  { english: "October", translations: ["octobre"] },
  { english: "November", translations: ["novembre"] },
  { english: "December", translations: ["décembre"] },
  { english: "month", translations: ["mois"] },
  { english: "year", translations: ["an", "année"] },
  { english: "week", translations: ["semaine"] },
  { english: "weekend", translations: ["week-end"] },

  // More time
  { english: "hour", translations: ["heure"] },
  { english: "minute", translations: ["minute"] },
  { english: "soon", translations: ["bientôt"] },
  { english: "late", translations: ["tard"] },
  { english: "early", translations: ["tôt"] },
  { english: "always", translations: ["toujours"] },
  { english: "never", translations: ["jamais"] },
  { english: "sometimes", translations: ["parfois", "quelquefois"] },
  { english: "often", translations: ["souvent"] },
  { english: "already", translations: ["déjà"] },
  { english: "still / yet", translations: ["encore", "toujours"] },
  { english: "again", translations: ["encore", "de nouveau"] },

  // More colours
  { english: "light blue", translations: ["bleu clair"] },

  // More body
  { english: "face", translations: ["visage"] },
  { english: "back", translations: ["dos"] },
  { english: "hair", translations: ["cheveux"] },
  { english: "teeth", translations: ["dents"] },
  { english: "finger", translations: ["doigt"] },
  { english: "shoulder", translations: ["épaule"] },
  { english: "knee", translations: ["genou"] },

  // More food
  { english: "beer", translations: ["bière"] },
  { english: "pasta", translations: ["pâtes"] },
  { english: "pizza", translations: ["pizza"] },
  { english: "orange (fruit)", translations: ["orange"] },
  { english: "banana", translations: ["banane"] },
  { english: "tomato", translations: ["tomate"] },
  { english: "onion", translations: ["oignon"] },
  { english: "garlic", translations: ["ail"] },
  { english: "salt", translations: ["sel"] },
  { english: "sugar", translations: ["sucre"] },
  { english: "oil", translations: ["huile"] },
  { english: "soup", translations: ["soupe"] },
  { english: "salad", translations: ["salade"] },
  { english: "chicken", translations: ["poulet"] },
  { english: "vegetables", translations: ["légumes"] },
  { english: "fruit", translations: ["fruit"] },
  { english: "butter", translations: ["beurre"] },
  { english: "ice cream", translations: ["glace"] },
  { english: "cake", translations: ["gâteau"] },
  { english: "chocolate", translations: ["chocolat"] },
  { english: "breakfast", translations: ["petit-déjeuner"] },
  { english: "lunch", translations: ["déjeuner"] },
  { english: "dinner", translations: ["dîner"] },

  // More infinitive verbs
  { english: "to know (a fact)", translations: ["savoir"] },
  { english: "to know (a person)", translations: ["connaître"] },
  { english: "to find", translations: ["trouver"] },
  { english: "to think", translations: ["penser"] },
  { english: "to listen", translations: ["écouter"] },
  { english: "to look at", translations: ["regarder"] },
  { english: "to feel / hear", translations: ["sentir", "entendre"] },
  { english: "to wait", translations: ["attendre"] },
  { english: "to call", translations: ["appeler"] },
  { english: "to ask", translations: ["demander"] },
  { english: "to leave", translations: ["partir", "laisser"] },
  { english: "to return", translations: ["retourner", "revenir"] },
  { english: "to enter", translations: ["entrer"] },
  { english: "to exit / go out", translations: ["sortir"] },
  { english: "to arrive", translations: ["arriver"] },
  { english: "to remember", translations: ["se souvenir"] },
  { english: "to forget", translations: ["oublier"] },
  { english: "to believe", translations: ["croire"] },
  { english: "to lose", translations: ["perdre"] },
  { english: "to become", translations: ["devenir"] },
  { english: "to bring / carry", translations: ["apporter", "porter"] },
  { english: "to put", translations: ["mettre"] },
  { english: "to try", translations: ["essayer"] },
  { english: "to use", translations: ["utiliser"] },
  { english: "to change", translations: ["changer"] },
  { english: "to finish", translations: ["finir"] },
  { english: "to start", translations: ["commencer"] },
  { english: "to play (a game)", translations: ["jouer"] },
  { english: "to sing", translations: ["chanter"] },
  { english: "to dance", translations: ["danser"] },
  { english: "to read", translations: ["lire"] },
  { english: "to write", translations: ["écrire"] },
  { english: "to walk", translations: ["marcher"] },
  { english: "to run", translations: ["courir"] },
  { english: "to drive", translations: ["conduire"] },
  { english: "to travel", translations: ["voyager"] },
  { english: "to pay", translations: ["payer"] },
  { english: "to buy", translations: ["acheter"] },
  { english: "to sell", translations: ["vendre"] },
  { english: "to help", translations: ["aider"] },
  { english: "to open", translations: ["ouvrir"] },
  { english: "to close", translations: ["fermer"] },
  { english: "to laugh", translations: ["rire"] },
  { english: "to cry", translations: ["pleurer"] },
  { english: "to smile", translations: ["sourire"] },
  { english: "to teach", translations: ["enseigner"] },
  { english: "to learn", translations: ["apprendre"] },
  { english: "to study", translations: ["étudier"] },
  { english: "to cook", translations: ["cuisiner"] },
  { english: "to wash", translations: ["laver"] },
  { english: "to clean", translations: ["nettoyer"] },
  { english: "to search", translations: ["chercher"] },
  { english: "to meet", translations: ["rencontrer"] },
  { english: "to show", translations: ["montrer"] },
  { english: "to send", translations: ["envoyer"] },
  { english: "to receive", translations: ["recevoir"] },
  { english: "to stay / remain", translations: ["rester"] },
  { english: "to continue", translations: ["continuer"] },
  { english: "to hope", translations: ["espérer"] },

  // être — present tense
  { english: "I am", translations: ["je suis"] },
  { english: "you are (singular)", translations: ["tu es"] },
  { english: "he is", translations: ["il est"] },
  { english: "she is", translations: ["elle est"] },
  { english: "we are", translations: ["nous sommes", "on est"] },
  { english: "you are (plural)", translations: ["vous êtes"] },
  { english: "they are", translations: ["ils sont", "elles sont"] },

  // avoir — present tense
  { english: "I have", translations: ["j'ai"] },
  { english: "you have (singular)", translations: ["tu as"] },
  { english: "he has", translations: ["il a"] },
  { english: "she has", translations: ["elle a"] },
  { english: "we have", translations: ["nous avons", "on a"] },
  { english: "you have (plural)", translations: ["vous avez"] },
  { english: "they have", translations: ["ils ont", "elles ont"] },

  // faire — present tense
  { english: "I do / I make", translations: ["je fais"] },
  { english: "you do / you make (singular)", translations: ["tu fais"] },
  { english: "he does / he makes", translations: ["il fait"] },
  { english: "she does / she makes", translations: ["elle fait"] },
  { english: "we do / we make", translations: ["nous faisons", "on fait"] },
  { english: "you do / you make (plural)", translations: ["vous faites"] },
  { english: "they do / they make", translations: ["ils font", "elles font"] },

  // aller — present tense
  { english: "I go", translations: ["je vais"] },
  { english: "you go (singular)", translations: ["tu vas"] },
  { english: "he goes", translations: ["il va"] },
  { english: "she goes", translations: ["elle va"] },
  { english: "we go", translations: ["nous allons", "on va"] },
  { english: "you go (plural)", translations: ["vous allez"] },
  { english: "they go", translations: ["ils vont", "elles vont"] },

  // vouloir — present tense
  { english: "I want", translations: ["je veux"] },
  { english: "you want (singular)", translations: ["tu veux"] },
  { english: "he wants", translations: ["il veut"] },
  { english: "she wants", translations: ["elle veut"] },
  { english: "we want", translations: ["nous voulons", "on veut"] },
  { english: "you want (plural)", translations: ["vous voulez"] },
  { english: "they want", translations: ["ils veulent", "elles veulent"] },

  // pouvoir — present tense
  { english: "I can", translations: ["je peux"] },
  { english: "you can (singular)", translations: ["tu peux"] },
  { english: "he can", translations: ["il peut"] },
  { english: "she can", translations: ["elle peut"] },
  { english: "we can", translations: ["nous pouvons", "on peut"] },
  { english: "you can (plural)", translations: ["vous pouvez"] },
  { english: "they can", translations: ["ils peuvent", "elles peuvent"] },

  // devoir — present tense
  { english: "I must / I have to", translations: ["je dois"] },
  { english: "you must (singular)", translations: ["tu dois"] },
  { english: "he must", translations: ["il doit"] },
  { english: "she must", translations: ["elle doit"] },
  { english: "we must", translations: ["nous devons", "on doit"] },
  { english: "you must (plural)", translations: ["vous devez"] },
  { english: "they must", translations: ["ils doivent", "elles doivent"] },

  // parler — present tense (regular -er model)
  { english: "I speak", translations: ["je parle"] },
  { english: "you speak (singular)", translations: ["tu parles"] },
  { english: "he speaks", translations: ["il parle"] },
  { english: "she speaks", translations: ["elle parle"] },
  { english: "we speak", translations: ["nous parlons", "on parle"] },
  { english: "you speak (plural)", translations: ["vous parlez"] },
  { english: "they speak", translations: ["ils parlent", "elles parlent"] },

  // finir — present tense (regular -ir model)
  { english: "I finish", translations: ["je finis"] },
  { english: "you finish (singular)", translations: ["tu finis"] },
  { english: "he finishes", translations: ["il finit"] },
  { english: "she finishes", translations: ["elle finit"] },
  { english: "we finish", translations: ["nous finissons", "on finit"] },
  { english: "you finish (plural)", translations: ["vous finissez"] },
  { english: "they finish", translations: ["ils finissent", "elles finissent"] },

  // More adjectives
  { english: "long", translations: ["long"] },
  { english: "short (length)", translations: ["court"] },
  { english: "tall / high", translations: ["grand", "haut"] },
  { english: "short (height)", translations: ["petit"] },
  { english: "fat", translations: ["gros"] },
  { english: "thin", translations: ["mince"] },
  { english: "warm", translations: ["tiède"] },
  { english: "clean", translations: ["propre"] },
  { english: "dirty", translations: ["sale"] },
  { english: "full", translations: ["plein"] },
  { english: "empty", translations: ["vide"] },
  { english: "open", translations: ["ouvert"] },
  { english: "closed", translations: ["fermé"] },
  { english: "rich", translations: ["riche"] },
  { english: "poor", translations: ["pauvre"] },
  { english: "sick / ill", translations: ["malade"] },
  { english: "healthy", translations: ["sain"] },
  { english: "strong", translations: ["fort"] },
  { english: "weak", translations: ["faible"] },
  { english: "light (weight)", translations: ["léger"] },
  { english: "heavy", translations: ["lourd"] },
  { english: "sweet", translations: ["sucré", "doux"] },
  { english: "salty", translations: ["salé"] },
  { english: "expensive", translations: ["cher"] },
  { english: "cheap", translations: ["bon marché"] },
  { english: "near", translations: ["près", "proche"] },
  { english: "far", translations: ["loin"] },
  { english: "right / correct", translations: ["correct", "juste"] },
  { english: "wrong", translations: ["faux", "incorrect"] },
  { english: "true", translations: ["vrai"] },
  { english: "important", translations: ["important"] },
  { english: "interesting", translations: ["intéressant"] },
  { english: "boring", translations: ["ennuyeux"] },
  { english: "funny / fun", translations: ["drôle", "amusant"] },
  { english: "ready", translations: ["prêt"] },
  { english: "free", translations: ["libre"] },

  // More places
  { english: "bathroom", translations: ["salle de bain"] },
  { english: "bedroom", translations: ["chambre"] },
  { english: "window", translations: ["fenêtre"] },
  { english: "bed", translations: ["lit"] },
  { english: "road / street", translations: ["rue", "route"] },
  { english: "country / nation", translations: ["pays"] },
  { english: "world", translations: ["monde"] },
  { english: "university", translations: ["université"] },
  { english: "hospital", translations: ["hôpital"] },
  { english: "hotel", translations: ["hôtel"] },
  { english: "shop / store", translations: ["magasin"] },
  { english: "market", translations: ["marché"] },
  { english: "airport", translations: ["aéroport"] },
  { english: "station", translations: ["gare"] },
  { english: "park", translations: ["parc"] },
  { english: "office", translations: ["bureau"] },
  { english: "library", translations: ["bibliothèque"] },
  { english: "pharmacy", translations: ["pharmacie"] },
  { english: "bank", translations: ["banque"] },
  { english: "museum", translations: ["musée"] },

  // Nature
  { english: "sun", translations: ["soleil"] },
  { english: "moon", translations: ["lune"] },
  { english: "sky", translations: ["ciel"] },
  { english: "sea", translations: ["mer"] },
  { english: "mountain", translations: ["montagne"] },
  { english: "river", translations: ["rivière", "fleuve"] },
  { english: "forest / wood", translations: ["forêt", "bois"] },
  { english: "flower", translations: ["fleur"] },
  { english: "tree", translations: ["arbre"] },
  { english: "rain", translations: ["pluie"] },
  { english: "snow", translations: ["neige"] },
  { english: "wind", translations: ["vent"] },
  { english: "fire", translations: ["feu"] },

  // More animals
  { english: "pig", translations: ["cochon"] },
  { english: "sheep", translations: ["mouton"] },

  // More transport
  { english: "aeroplane", translations: ["avion"] },
  { english: "bicycle", translations: ["vélo", "bicyclette"] },
  { english: "boat", translations: ["bateau"] },

  // People & roles
  { english: "husband", translations: ["mari"] },
  { english: "wife", translations: ["femme"] },
  { english: "parents", translations: ["parents"] },
  { english: "doctor", translations: ["médecin", "docteur"] },
  { english: "teacher", translations: ["professeur"] },
  { english: "student", translations: ["étudiant"] },
  { english: "lawyer", translations: ["avocat"] },

  // Common nouns
  { english: "life", translations: ["vie"] },
  { english: "love", translations: ["amour"] },
  { english: "problem", translations: ["problème"] },
  { english: "idea", translations: ["idée"] },
  { english: "word", translations: ["mot"] },
  { english: "question", translations: ["question"] },
  { english: "answer", translations: ["réponse"] },
  { english: "story / history", translations: ["histoire"] },
  { english: "money", translations: ["argent"] },
  { english: "work / job", translations: ["travail"] },
  { english: "music", translations: ["musique"] },
  { english: "book", translations: ["livre"] },
  { english: "language", translations: ["langue"] },
  { english: "name", translations: ["nom"] },
  { english: "place / spot", translations: ["endroit", "place"] },
  { english: "trip / journey", translations: ["voyage"] },
  { english: "phone", translations: ["téléphone"] },
  { english: "message", translations: ["message"] },
  { english: "film / movie", translations: ["film"] },
  { english: "game", translations: ["jeu"] },
  { english: "sport", translations: ["sport"] },
  { english: "of course", translations: ["bien sûr"] },
  { english: "maybe", translations: ["peut-être"] },
  { english: "also / too", translations: ["aussi"] },
  { english: "only", translations: ["seulement"] },
  { english: "more", translations: ["plus"] },
  { english: "less", translations: ["moins"] },
  { english: "before", translations: ["avant"] },
  { english: "after", translations: ["après"] },
  { english: "without", translations: ["sans"] },
  { english: "in front of", translations: ["devant"] },
  { english: "behind", translations: ["derrière"] },
  { english: "together", translations: ["ensemble"] },
  { english: "something", translations: ["quelque chose"] },
  { english: "someone", translations: ["quelqu'un"] },
  { english: "nothing", translations: ["rien"] },
  { english: "everyone", translations: ["tout le monde"] },
];

const frenchWordsB1_new = [
  // Advanced vocabulary
  { english: "advice", translations: ["conseil"] },
  { english: "choice", translations: ["choix"] },
  { english: "effort", translations: ["effort"] },
  { english: "result", translations: ["résultat"] },
  { english: "opinion", translations: ["avis", "opinion"] },
  { english: "relationship", translations: ["relation", "rapport"] },
  { english: "society", translations: ["société"] },
  { english: "environment", translations: ["environnement"] },
  { english: "government", translations: ["gouvernement"] },
  { english: "experience", translations: ["expérience"] },
  { english: "knowledge", translations: ["connaissance"] },
  { english: "memory", translations: ["mémoire", "souvenir"] },
  { english: "freedom", translations: ["liberté"] },
  { english: "power", translations: ["pouvoir"] },
  { english: "success", translations: ["succès"] },
  { english: "failure", translations: ["échec"] },
  { english: "danger", translations: ["danger"] },
  { english: "agreement", translations: ["accord"] },
  { english: "surprise", translations: ["surprise"] },
  { english: "advantage", translations: ["avantage"] },

  // Advanced adjectives
  { english: "serious", translations: ["sérieux"] },
  { english: "strange / odd", translations: ["étrange", "bizarre"] },
  { english: "dangerous", translations: ["dangereux"] },
  { english: "incredible", translations: ["incroyable"] },
  { english: "perfect", translations: ["parfait"] },
  { english: "excellent", translations: ["excellent"] },
  { english: "fantastic", translations: ["fantastique"] },
  { english: "necessary", translations: ["nécessaire"] },
  { english: "possible", translations: ["possible"] },
  { english: "impossible", translations: ["impossible"] },
  { english: "quiet / silent", translations: ["calme", "silencieux"] },

  // Passé composé — avoir verbs
  { english: "I spoke / I have spoken", translations: ["j'ai parlé"] },
  { english: "you spoke (singular)", translations: ["tu as parlé"] },
  { english: "he spoke", translations: ["il a parlé"] },
  { english: "she spoke", translations: ["elle a parlé"] },
  { english: "we spoke", translations: ["nous avons parlé", "on a parlé"] },
  { english: "you spoke (plural)", translations: ["vous avez parlé"] },
  { english: "they spoke", translations: ["ils ont parlé", "elles ont parlé"] },

  { english: "I ate / I have eaten", translations: ["j'ai mangé"] },
  { english: "you ate (singular)", translations: ["tu as mangé"] },
  { english: "he ate", translations: ["il a mangé"] },
  { english: "she ate", translations: ["elle a mangé"] },
  { english: "we ate", translations: ["nous avons mangé", "on a mangé"] },
  { english: "they ate", translations: ["ils ont mangé", "elles ont mangé"] },

  { english: "I finished / I have finished", translations: ["j'ai fini"] },
  { english: "you finished (singular)", translations: ["tu as fini"] },
  { english: "he finished", translations: ["il a fini"] },
  { english: "she finished", translations: ["elle a fini"] },
  { english: "we finished", translations: ["nous avons fini", "on a fini"] },
  { english: "they finished", translations: ["ils ont fini", "elles ont fini"] },

  { english: "I did / I have done", translations: ["j'ai fait"] },
  { english: "you did (singular)", translations: ["tu as fait"] },
  { english: "he did", translations: ["il a fait"] },
  { english: "she did", translations: ["elle a fait"] },
  { english: "we did", translations: ["nous avons fait", "on a fait"] },
  { english: "they did", translations: ["ils ont fait", "elles ont fait"] },

  { english: "I saw / I have seen", translations: ["j'ai vu"] },
  { english: "you saw (singular)", translations: ["tu as vu"] },
  { english: "he saw", translations: ["il a vu"] },
  { english: "she saw", translations: ["elle a vu"] },
  { english: "we saw", translations: ["nous avons vu", "on a vu"] },
  { english: "they saw", translations: ["ils ont vu", "elles ont vu"] },

  { english: "I drank / I have drunk", translations: ["j'ai bu"] },
  { english: "you drank (singular)", translations: ["tu as bu"] },
  { english: "he drank", translations: ["il a bu"] },
  { english: "she drank", translations: ["elle a bu"] },
  { english: "we drank", translations: ["nous avons bu", "on a bu"] },
  { english: "they drank", translations: ["ils ont bu", "elles ont bu"] },

  // Passé composé — être verbs (gender agreement)
  { english: "I went / I have gone", translations: ["je suis allé", "je suis allée"] },
  { english: "he went", translations: ["il est allé"] },
  { english: "she went", translations: ["elle est allée"] },
  { english: "we went", translations: ["nous sommes allés", "on est allé"] },
  { english: "they went", translations: ["ils sont allés", "elles sont allées"] },

  { english: "I came / I have come", translations: ["je suis venu", "je suis venue"] },
  { english: "he came", translations: ["il est venu"] },
  { english: "she came", translations: ["elle est venue"] },
  { english: "we came", translations: ["nous sommes venus", "on est venu"] },
  { english: "they came", translations: ["ils sont venus", "elles sont venues"] },

  { english: "I arrived / I have arrived", translations: ["je suis arrivé", "je suis arrivée"] },
  { english: "he arrived", translations: ["il est arrivé"] },
  { english: "she arrived", translations: ["elle est arrivée"] },
  { english: "we arrived", translations: ["nous sommes arrivés", "on est arrivé"] },
  { english: "they arrived", translations: ["ils sont arrivés", "elles sont arrivées"] },

  { english: "I left / I have left", translations: ["je suis parti", "je suis partie"] },
  { english: "he left", translations: ["il est parti"] },
  { english: "she left", translations: ["elle est partie"] },
  { english: "we left", translations: ["nous sommes partis", "on est parti"] },
  { english: "they left", translations: ["ils sont partis", "elles sont parties"] },

  // Futur simple
  { english: "I will speak", translations: ["je parlerai"] },
  { english: "you will speak (singular)", translations: ["tu parleras"] },
  { english: "he will speak", translations: ["il parlera"] },
  { english: "she will speak", translations: ["elle parlera"] },
  { english: "we will speak", translations: ["nous parlerons", "on parlera"] },
  { english: "you will speak (plural)", translations: ["vous parlerez"] },
  { english: "they will speak", translations: ["ils parleront", "elles parleront"] },

  { english: "I will go", translations: ["j'irai"] },
  { english: "you will go (singular)", translations: ["tu iras"] },
  { english: "he will go", translations: ["il ira"] },
  { english: "she will go", translations: ["elle ira"] },
  { english: "we will go", translations: ["nous irons", "on ira"] },
  { english: "they will go", translations: ["ils iront", "elles iront"] },

  { english: "I will be", translations: ["je serai"] },
  { english: "you will be (singular)", translations: ["tu seras"] },
  { english: "he will be", translations: ["il sera"] },
  { english: "she will be", translations: ["elle sera"] },
  { english: "we will be", translations: ["nous serons", "on sera"] },
  { english: "they will be", translations: ["ils seront", "elles seront"] },

  { english: "I will have", translations: ["j'aurai"] },
  { english: "you will have (singular)", translations: ["tu auras"] },
  { english: "he will have", translations: ["il aura"] },
  { english: "she will have", translations: ["elle aura"] },
  { english: "we will have", translations: ["nous aurons", "on aura"] },
  { english: "they will have", translations: ["ils auront", "elles auront"] },

  { english: "I will come", translations: ["je viendrai"] },
  { english: "you will come (singular)", translations: ["tu viendras"] },
  { english: "he will come", translations: ["il viendra"] },
  { english: "she will come", translations: ["elle viendra"] },
  { english: "we will come", translations: ["nous viendrons", "on viendra"] },
  { english: "they will come", translations: ["ils viendront", "elles viendront"] },

  // Imparfait
  { english: "I used to speak / I was speaking", translations: ["je parlais"] },
  { english: "you used to speak (singular)", translations: ["tu parlais"] },
  { english: "he used to speak / he was speaking", translations: ["il parlait"] },
  { english: "she used to speak / she was speaking", translations: ["elle parlait"] },
  { english: "we used to speak", translations: ["nous parlions", "on parlait"] },
  { english: "you used to speak (plural)", translations: ["vous parliez"] },
  { english: "they used to speak", translations: ["ils parlaient", "elles parlaient"] },

  { english: "I used to be / I was", translations: ["j'étais"] },
  { english: "you used to be (singular)", translations: ["tu étais"] },
  { english: "he used to be / he was", translations: ["il était"] },
  { english: "she used to be / she was", translations: ["elle était"] },
  { english: "we used to be", translations: ["nous étions", "on était"] },
  { english: "they used to be", translations: ["ils étaient", "elles étaient"] },

  { english: "I used to have / I had", translations: ["j'avais"] },
  { english: "you used to have (singular)", translations: ["tu avais"] },
  { english: "he used to have / he had", translations: ["il avait"] },
  { english: "she used to have / she had", translations: ["elle avait"] },
  { english: "we used to have", translations: ["nous avions", "on avait"] },
  { english: "they used to have", translations: ["ils avaient", "elles avaient"] },

  { english: "I used to go / I was going", translations: ["j'allais"] },
  { english: "you used to go (singular)", translations: ["tu allais"] },
  { english: "he used to go / he was going", translations: ["il allait"] },
  { english: "she used to go / she was going", translations: ["elle allait"] },
  { english: "we used to go", translations: ["nous allions", "on allait"] },
  { english: "they used to go", translations: ["ils allaient", "elles allaient"] },

  { english: "I used to want / I wanted", translations: ["je voulais"] },
  { english: "you used to want (singular)", translations: ["tu voulais"] },
  { english: "he used to want / he wanted", translations: ["il voulait"] },
  { english: "she used to want / she wanted", translations: ["elle voulait"] },
  { english: "we used to want", translations: ["nous voulions", "on voulait"] },
  { english: "they used to want", translations: ["ils voulaient", "elles voulaient"] },
];

const frenchLevels = {
  a1: frenchWordsA1,
  a2: [...frenchWordsA1, ...frenchWordsA2_new],
  b1: [...frenchWordsA1, ...frenchWordsA2_new, ...frenchWordsB1_new],
};
